# path: ./docker-compose.yml

version: '3.1'
services:
  strapi_sports_board:
    container_name: sports_board_backend_strapi
    build: .
    image: sports_board_image
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '1339:1337'
    networks:
      - sports-board-strapi


volumes:
  sportsBoard-strapi-data:

networks:
  sports-board-strapi:
    driver: bridge
