# path: ./Dockerfile

FROM node:14-alpine
# Installing libvips-dev for sharp Compatibility
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}
WORKDIR /opt/
COPY ./package.json ./package-lock.json ./
RUN npm install
WORKDIR .
RUN npm run build
EXPOSE 1337
CMD ["npm", "run", "develop"]
 