name: Frontend Deployment
on:
    workflow_dispatch:
    # push:
    #     paths:
    #         - "frontend/**"
    #     branches:
    #         - "main"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Establish ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        script: |
            cd /webapps/sports_board_website
            git fetch deploy2
            git checkout deploy2
            git pull
            git status
            docker-compose -f docker-compose.prod.yaml up -d --build
